import { NextPage } from 'next';
import Head from 'next/head';
import React, { useState } from 'react'
import { useSelector } from 'react-redux';
import Button from '../components/Button';
import CartItem from '../components/CartItem';
import Container from '../components/Container';
import Popup from '../components/Popup';
import { RootState } from '../store';
import { UserInfo } from '../types';
import { useAddOrderMutation } from '../slices/apiSlice';

const Cart: NextPage = () => {
    const [togglePopupState, setTogglePopupState] = useState(false);
    const [addOrder, result] = useAddOrderMutation()
    const cart = useSelector((state: RootState) => state.cart);
    const products = cart.products;
    const currencyIcon = '$';

    // total amount & vat
    const subTotal = cart.total;
    const totalCartVat = cart.totalVat;
    const totalCartAmount = subTotal + totalCartVat;

    // user details popup
    const togglePopup = (toggle: boolean) => {
        setTogglePopupState(toggle);
    }

    // send order data to api
    const checkoutHandler = async (userInfo: UserInfo) => {
        const orderInfo = {
            customer: userInfo,
            calculation: {
                price: subTotal,
                vat: totalCartVat,
                total: totalCartAmount

            },
            items: products
        }
        await addOrder(orderInfo);
    }

    return (
        <>
            <Head>
                <title>Cart - Munchies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-full flex items-center justify-center p-4 md:p-16'>
                {togglePopupState &&
                    <Popup
                        result={result}
                        togglePopup={togglePopup}
                        checkoutHandler={checkoutHandler}
                    />
                }
                <Container>
                    <div className='w-full grid grid-cols-1 md:grid-cols-7 gap-12'>
                        <div className='col-span-5'>
                            <h1 className='text-4xl font-bold'>Shopping Cart</h1>
                            <div className='w-full flex items-center justify-between border-b mt-8 font-medium text-gray-900'>
                                <div>Product</div>
                                <div className='flex gap-8'>
                                    <span>Quantity</span>
                                    <span>Total Price</span>
                                    <span>Vat</span>
                                </div>
                            </div>
                            <div className='w-full'>
                                {products.length > 0 ?
                                    products.map(product => (
                                        <CartItem
                                            key={product.id}
                                            product={product}
                                        />
                                    )) :
                                    <div className='w-full text-center text-gray-500 p-4'>Cart is empty</div>
                                }
                            </div>
                        </div>
                        <div className='col-span-7 md:col-span-2 w-full h-full'>
                            <div className="sticky top-2 w-full h-full max-h-[50vh] bg-gradient-to-br from-blue-900 to-gray-900 rounded-ten p-6">

                                <div className='h-full flex flex-col justify-between text-white text-base space-y-4'>
                                    <div className='border-b border-gray-500 pb-2'>
                                        <h2 className='text-3xl text-white'>Payment Info.</h2>
                                    </div>
                                    <div className='flex flex-col gap-2'>
                                        <div className='flex items-center justify-between px-2'>
                                            <span className='font-semibold'>Subtotal:</span>
                                            <span>{currencyIcon}{subTotal}</span>
                                        </div>
                                        <div className='flex items-center justify-between px-2'>
                                            <span className='font-semibold'>Vat:</span>
                                            <span>{currencyIcon}{totalCartVat}</span>
                                        </div>
                                        <hr />
                                        <div className='flex items-center justify-between px-2'>
                                            <span className='font-semibold'>Total:</span>
                                            <span>{currencyIcon}{totalCartAmount}</span>
                                        </div>
                                        <Button onclick={() => togglePopup(true)}>
                                            Checkout
                                        </Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </Container>
            </div>
        </>
    )
}

export default Cart;
