import Head from 'next/head'
import SearchComponent from '../components/SearchComponent'
import FilterComponent from '../components/FilterComponent'
import HeroComponent from '../components/HeroComponent'
import BlogComponent from '../components/BlogComponent'
import ContactComponent from '../components/ContactComponent'
import Footer from '../components/Footer'
import useSWR from 'swr'
import axios from 'axios'
import { TApiAllProductsResponse } from '../types'


axios.defaults.baseURL = 'https://munchies-api.up.railway.app';

const fetcher = (url: string) => axios.get(url).then(res => res.data);

export default function Home() {
  const { data, error } = useSWR<TApiAllProductsResponse[]>('/products/', fetcher);



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full'>
        <HeroComponent />
        {data &&
          <FilterComponent data={data} />
        }
        <BlogComponent />
        <ContactComponent />
        <Footer />
      </main>
    </>
  )
}
