import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react'
import Container from '../components/Container';
import { useGetOrdersQuery } from '../slices/apiSlice';

const Orders: NextPage = () => {
    const { data: ordersData } = useGetOrdersQuery()

    return (
        <>
            <Head>
                <title>Orders - Munchies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-full flex items-center justify-center p-4 md:p-16'>
                <Container>
                    <div className='p-4 md:p-0'>
                        <h1 className='text-gray-700 text-3xl font-semibold mb-4'>Orders.</h1>
                        <table className="min-w-full divide-y divide-gray-300 rounded-md overflow-hidden shadow">
                            <thead className="bg-gray-50">
                                <tr className='uppercase border-t'>
                                    <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                                        <span className="sr-only">Image</span>
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-700">
                                        Item
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-700">
                                        Ordered by
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-700">
                                        Quantity
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-700">
                                        Price
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-700">
                                        Order date
                                    </th>

                                </tr>
                            </thead>

                            <tbody className="divide-y divide-gray-200 bg-white">
                                {ordersData?.map((orders) => (
                                    orders.items.map((item, idx) => (
                                        <tr key={idx}>
                                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                                                <div className='relative w-20 h-16 object-contain rounded-lg overflow-hidden'>
                                                    <Image
                                                        src={item.image}
                                                        fill
                                                        alt={item.name}
                                                    />
                                                </div>
                                            </td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{item.name}</td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{orders.customer.name}</td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{item.quantity}</td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{item.price * item.quantity!}</td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                                {(new Date(orders?.createdAt))?.toLocaleDateString('pt-PT')}
                                            </td>
                                        </tr>
                                    ))
                                ))}
                            </tbody>


                        </table>
                        {ordersData && !(ordersData?.length > 0) &&
                            <p className='w-full text-center p-4 text-gray-500'>
                                No orders
                            </p>
                        }
                    </div>
                </Container>
            </div>
        </>
    )
}

export default Orders;
